#!/bin/bash

/opt/rocks/bin/rocks "add host" sidewinder-devel cpus=1 rack=0 rank=1 membership="Development Appliance" os=linux
/opt/rocks/bin/rocks set host runaction sidewinder-devel action=os
/opt/rocks/bin/rocks set host installaction sidewinder-devel action=install
/opt/rocks/bin/rocks set host boot sidewinder-devel action=os
/opt/rocks/bin/rocks add host interface sidewinder-devel eth0
/opt/rocks/bin/rocks set host interface ip sidewinder-devel eth0 10.1.255.253
/opt/rocks/bin/rocks set host interface name sidewinder-devel eth0 sidewinder-devel
/opt/rocks/bin/rocks set host interface mac sidewinder-devel eth0 08:00:27:8d:9b:a4
/opt/rocks/bin/rocks set host interface subnet sidewinder-devel eth0 private
/opt/rocks/bin/rocks add host interface sidewinder-devel eth1
/opt/rocks/bin/rocks set host interface ip sidewinder-devel eth1 192.168.16.17
/opt/rocks/bin/rocks set host interface name sidewinder-devel eth1 sidewinder-devel
/opt/rocks/bin/rocks set host interface mac sidewinder-devel eth1 08:00:27:b2:69:05
/opt/rocks/bin/rocks set host interface subnet sidewinder-devel eth1 public
