#!/bin/bash

/opt/rocks/bin/rocks "add host" sidewinder-login cpus=1 rack=0 rank=0 membership=Login os=linux
/opt/rocks/bin/rocks set host runaction sidewinder-login action=os
/opt/rocks/bin/rocks set host installaction sidewinder-login action=install
/opt/rocks/bin/rocks set host boot sidewinder-login action=os
/opt/rocks/bin/rocks add host interface sidewinder-login eth0
/opt/rocks/bin/rocks set host interface ip sidewinder-login eth0 10.1.255.254
/opt/rocks/bin/rocks set host interface name sidewinder-login eth0 sidewinder-login
/opt/rocks/bin/rocks set host interface mac sidewinder-login eth0 08:00:27:45:f5:5f
/opt/rocks/bin/rocks set host interface subnet sidewinder-login eth0 private
/opt/rocks/bin/rocks add host interface sidewinder-login eth1
/opt/rocks/bin/rocks set host interface ip sidewinder-login eth1 192.168.16.16
/opt/rocks/bin/rocks set host interface name sidewinder-login eth1 sidewinder-login
/opt/rocks/bin/rocks set host interface mac sidewinder-login eth1 08:00:27:c0:39:c5
/opt/rocks/bin/rocks set host interface subnet sidewinder-login eth1 public
