#!/bin/bash

/opt/rocks/bin/rocks "add host" sandboa-devel cpus=1 rack=0 rank=1 membership="Development Appliance" os=linux
/opt/rocks/bin/rocks set host runaction sandboa-devel action=os
/opt/rocks/bin/rocks set host installaction sandboa-devel action=install
/opt/rocks/bin/rocks set host boot sandboa-devel action=os
/opt/rocks/bin/rocks add host interface sandboa-devel eth0
/opt/rocks/bin/rocks set host interface ip sandboa-devel eth0 10.1.255.253
/opt/rocks/bin/rocks set host interface name sandboa-devel eth0 sandboa-devel
/opt/rocks/bin/rocks set host interface mac sandboa-devel eth0 08:00:27:8d:9b:a4
/opt/rocks/bin/rocks set host interface subnet sandboa-devel eth0 private
/opt/rocks/bin/rocks add host interface sandboa-devel eth1
/opt/rocks/bin/rocks set host interface ip sandboa-devel eth1 192.168.16.17
/opt/rocks/bin/rocks set host interface name sandboa-devel eth1 sandboa-devel
/opt/rocks/bin/rocks set host interface mac sandboa-devel eth1 08:00:27:b2:69:05
/opt/rocks/bin/rocks set host interface subnet sandboa-devel eth1 public
